stateDiagram-v2
   [*] --> Waiting: switched on  
  Waiting --> HeadingToDestination: buttonPress  
  HeadingToDestination --> Waiting: buttonPress  
  HeadingToDestination --> Waiting: drivingTimeout
  