stateDiagram-v2
   [*] --> Waiting: switched on  
  Waiting --> HeadingToDestinationFast: buttonPress  
  HeadingToDestinationFast --> HeadingToDestinationFast: clearPathDetected
  HeadingToDestinationFast --> HeadingToDestinationSlow: distantObjectDetected
  HeadingToDestinationSlow --> HeadingToDestinationFast: clearPathDetected
  HeadingToDestinationSlow --> Stuck: obstructionDetected
  Stuck --> HeadingToDestinationFast: buttonPress
  HeadingToDestinationFast --> Waiting: buttonPress  
  HeadingToDestinationFast --> Waiting: drivingTimeout
  